/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrashToCashSystem;

import javax.swing.JFrame;
public class DBOptions extends javax.swing.JFrame {

    /**
     * Creates new form DBOptions
     */
    public DBOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidebar14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        btnRedeemPoints29 = new javax.swing.JButton();
        btnRedeemPoints30 = new javax.swing.JButton();
        btnDataTrash14 = new javax.swing.JButton();
        btnInputForm14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRedeem = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        btnItem = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(238, 248, 235));

        jLabel1.setBackground(new java.awt.Color(238, 248, 235));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/TRASH TO CASH LOGO.png"))); // NOI18N
        jLabel1.setIconTextGap(0);
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 32767));

        sidebar14.setBackground(new java.awt.Color(218, 243, 210));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/100x100seal.png"))); // NOI18N
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnRedeemPoints29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints29.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints29.setText("ITEMS AND SECTORS");
        btnRedeemPoints29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints29.setFocusPainted(false);
        btnRedeemPoints29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints29ActionPerformed(evt);
            }
        });

        btnRedeemPoints30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints30.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints30.setText("MEMBERS");
        btnRedeemPoints30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints30.setFocusPainted(false);
        btnRedeemPoints30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints30ActionPerformed(evt);
            }
        });

        btnDataTrash14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataTrash14.setForeground(new java.awt.Color(68, 105, 74));
        btnDataTrash14.setText("DATABASES");
        btnDataTrash14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTrash14.setFocusPainted(false);
        btnDataTrash14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataTrash14MouseExited(evt);
            }
        });
        btnDataTrash14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTrash14ActionPerformed(evt);
            }
        });

        btnInputForm14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInputForm14.setForeground(new java.awt.Color(68, 105, 74));
        btnInputForm14.setText("INPUT FORM");
        btnInputForm14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputForm14.setFocusPainted(false);
        btnInputForm14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputForm14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebar14Layout = new javax.swing.GroupLayout(sidebar14);
        sidebar14.setLayout(sidebar14Layout);
        sidebar14Layout.setHorizontalGroup(
            sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar14Layout.createSequentialGroup()
                .addGroup(sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputForm14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(btnDataTrash14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebar14Layout.setVerticalGroup(
            sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebar14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel42)
                .addGap(80, 80, 80)
                .addComponent(btnDataTrash14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnInputForm14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(238, 248, 235));

        btnRedeem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeem.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeem.setText("REDEEM TRANSACTIONS");
        btnRedeem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeem.setFocusPainted(false);
        btnRedeem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransfer.setForeground(new java.awt.Color(68, 105, 74));
        btnTransfer.setText("TRANSFER TRANSACTIONS");
        btnTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransfer.setFocusPainted(false);
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAll.setForeground(new java.awt.Color(68, 105, 74));
        btnAll.setText("ALL TRANSACTIONS");
        btnAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAll.setFocusPainted(false);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        btnItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnItem.setForeground(new java.awt.Color(68, 105, 74));
        btnItem.setText("MEMBERS' DEPOSITED ITEMS");
        btnItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem.setFocusPainted(false);

        btnDeposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(68, 105, 74));
        btnDeposit.setText("DEPOSIT TRANSACTIONS");
        btnDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeposit.setFocusPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnItem)
                .addGap(113, 113, 113)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnRedeem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRedeem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sidebar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        TransferTransactions opt = new TransferTransactions();
        opt.setVisible(true);
        opt.setTitle("Transfer Transactions");
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnRedeemPoints29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints29ActionPerformed
        // TODO add your handling code here:

        Options opt = new Options();
        opt.setVisible(true);
        opt.setTitle("Items and Sectors");
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints29ActionPerformed

    private void btnRedeemPoints30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints30ActionPerformed
        // TODO add your handling code here:
        Member member = new Member();
        member.setVisible(true);
        member.setTitle("Members' Records");
        member.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        member.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints30ActionPerformed

    private void btnDataTrash14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataTrash14MouseExited

    }//GEN-LAST:event_btnDataTrash14MouseExited

    private void btnDataTrash14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTrash14ActionPerformed
        DBOptions database = new DBOptions();
        database.setVisible(true);
        database.setTitle("Databases");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnDataTrash14ActionPerformed

    private void btnInputForm14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputForm14ActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.setTitle("Input Form");
        input.pack();
        input.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        input.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnInputForm14ActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
        TransactionList database = new TransactionList();
        database.setVisible(true);
        database.setTitle("Transaction List");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnRedeemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemActionPerformed
        // TODO add your handling code here:
        RedeemTransactions database = new RedeemTransactions();
        database.setVisible(true);
        database.setTitle("Redeem Transactions");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDataTrash14;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnInputForm14;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnRedeem;
    private javax.swing.JButton btnRedeemPoints29;
    private javax.swing.JButton btnRedeemPoints30;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel sidebar14;
    // End of variables declaration//GEN-END:variables
}
