/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrashToCashSystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Diogracias
 */
public class Member extends javax.swing.JFrame {

    Connection connect;
    PreparedStatement pre;
    ResultSet rs;
    DefaultTableModel model;
    
    public Member() {
        initComponents();
        display();
        date();
        populateSector();
        rowCount();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void populateSector(){
        try {
            String populateSector = "SELECT * FROM sector ";
            
            pre = (PreparedStatement) connect.prepareStatement(populateSector);
            rs = pre.executeQuery();
            
            while (rs.next()){
                cbSector.addItem(rs.getString("sector"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(InputForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void rowCount() {
        model = (DefaultTableModel) tblTable.getModel();
        int row = model.getRowCount();
        tfRowCount.setText(Integer.toString(row));

    }
    
    public void cbBarangay(){
    String sql = "SELECT * FROM datarecord where barangay LIKE '" + cbBarangayFilter.getSelectedItem().toString() + "'";
        
        try{
            pre = connect.prepareStatement(sql);
            rs = pre.executeQuery();
            tblTable.setModel(DbUtils.resultSetToTableModel(rs));
            tblTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            rowCount();
            
        }catch (SQLException e)
        {
            JOptionPane.showMessageDialog (null, e);
        }
}
    
    public String date(){
        
        String date;
        
        if (cbDate.isSelected()){
            tfIDNum.setEditable(false);
            date = (java.time.LocalDate.now().toString());
        }else {
            date = tfDate.getText();
        }
        
        return date;
    }
    
    private void display (){
        try {
            String display = "SELECT * FROM members";
            
            connect = DatabaseConnection.connectionDB();
            
            pre = (PreparedStatement) connect.prepareStatement(display);
            rs = pre.executeQuery();
            
            model = (DefaultTableModel) tblTable.getModel();
            model.setRowCount(0);
            
            TableColumn col1 = tblTable.getColumnModel().getColumn(1);
            col1.setPreferredWidth(130);
            
            while (rs.next()){
                
                
                model.addRow(new Object[]{
                    
                    rs.getString("memberID"),
                    rs.getString("name"),
                    rs.getString("barangay"),
                    rs.getString("sector"),
                    rs.getString("date")
                        
                });
                
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void filter(String query){
        model = (DefaultTableModel) tblTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (model);
        tblTable.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter (query));
    }
    
    private JFrame frame;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbDate = new javax.swing.JCheckBox();
        tfDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbBarangayFilter = new javax.swing.JComboBox<>();
        lblBarangay5 = new javax.swing.JLabel();
        tfRowCount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfIDNum = new javax.swing.JTextField();
        cbBarangay = new javax.swing.JComboBox<>();
        cbSector = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblBarangay = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRedeemPoints2 = new javax.swing.JButton();
        btnRedeemPoints1 = new javax.swing.JButton();
        btnDataTrash = new javax.swing.JButton();
        btnInputForm = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 248, 235));

        main.setBackground(new java.awt.Color(238, 248, 235));
        main.setPreferredSize(new java.awt.Dimension(1127, 686));

        center.setBackground(new java.awt.Color(238, 248, 235));
        center.setPreferredSize(new java.awt.Dimension(898, 674));

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Barangay", "Sector", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        jLabel4.setBackground(new java.awt.Color(238, 248, 235));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/TRASH TO CASH LOGO SMALL 2.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerifyInputWhenFocusTarget(false);

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 105, 74));
        jLabel8.setText("Search ID Number:");

        cbDate.setText("Auto-Generated");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 105, 74));
        jLabel9.setText("Date:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 105, 74));
        jLabel5.setText("Filter: Barangay");

        cbBarangayFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "ADYA", "ANILAO", "ANILAO-LABAC", "ANTIPOLO DEL NORTE", "ANTIPOLO DEL SUR", "BAGONG POOK", "BALINTAWAK", "BANAYBANAY", "BARANGAY 12", "BOLBOK", "BUGTONG NA PULO", "BULACNIN", "BULAKLAKAN", "CALAMIAS", "CUMBA", "DAGATAN", "HALANG", "INOSLOBAN", "KUYAMNGGI", "LATAG", "LODLOD", "LUMBANG", "MABINI", "MALAGONLONG", "MALITLIT", "MARAUOY", "MATAAS NA LUPA", "MUNTING PULO", "PAGOLINGIN BATA", "PAGOLINGIN EAST", "PAGOLINGIN WEST", "PANGAO", "PINAGKAWITAN", "PINAGTONGULAN", "PLARIDEL", "POBLACION BARANGAY 1", "POBLACION BARANGAY 2", "POBLACION BARANGAY 3 ", "POBLACION BARANGAY 4", "POBLACION BARANGAY 5", "POBLACION BARANGAY 6", "POBLACION BARANGAY 7", "POBLACION BARANGAY 8", "POBLACION BARANGAY 9", "POBLACION BARANGAY 9-A", "POBLACION BARANGAY 10", "POBLACION BARANGAY 11", "PUSIL", "QUEZON", "RIZAL", "SABANG", "SAMPAGUITA", "SAN BENITO", "SAN CARLOS", "SAN CELESTINO", "SAN FRANSCISCO", "SAN GUILLERMO", "SAN JOSE", "SAN LUCAS", "SAN SALVADOR", "SAN SEBASTIAN", "SANTO NINO", "SANTO TORIBIO", "SAPAC", "SICO", "TALISAY", "TAMBO", "TANGOB", "TANGUAY", "TIBIG", "TIPACAN" }));
        cbBarangayFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangayFilterActionPerformed(evt);
            }
        });

        lblBarangay5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblBarangay5.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay5.setText("No. of Results:");

        tfRowCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRowCount.setText("0");

        jPanel1.setBackground(new java.awt.Color(196, 226, 187));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 105, 74));
        jLabel3.setText("Member ID Number:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 105, 74));
        jLabel2.setText("Name :");

        tfIDNum.setEditable(false);
        tfIDNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDNumActionPerformed(evt);
            }
        });

        cbBarangay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "ADYA", "ANILAO", "ANILAO-LABAC", "ANTIPOLO DEL NORTE", "ANTIPOLO DEL SUR", "BAGONG POOK", "BALINTAWAK", "BANAYBANAY", "BARANGAY 12", "BOLBOK", "BUGTONG NA PULO", "BULACNIN", "BULAKLAKAN", "CALAMIAS", "CUMBA", "DAGATAN", "HALANG", "INOSLOBAN", "KUYAMNGGI", "LATAG", "LODLOD", "LUMBANG", "MABINI", "MALAGONLONG", "MALITLIT", "MARAUOY", "MATAAS NA LUPA", "MUNTING PULO", "PAGOLINGIN BATA", "PAGOLINGIN EAST", "PAGOLINGIN WEST", "PANGAO", "PINAGKAWITAN", "PINAGTONGULAN", "PLARIDEL", "POBLACION BARANGAY 1", "POBLACION BARANGAY 2", "POBLACION BARANGAY 3 ", "POBLACION BARANGAY 4", "POBLACION BARANGAY 5", "POBLACION BARANGAY 6", "POBLACION BARANGAY 7", "POBLACION BARANGAY 8", "POBLACION BARANGAY 9", "POBLACION BARANGAY 9-A", "POBLACION BARANGAY 10", "POBLACION BARANGAY 11", "PUSIL", "QUEZON", "RIZAL", "SABANG", "SAMPAGUITA", "SAN BENITO", "SAN CARLOS", "SAN CELESTINO", "SAN FRANSCISCO", "SAN GUILLERMO", "SAN JOSE", "SAN LUCAS", "SAN SALVADOR", "SAN SEBASTIAN", "SANTO NINO", "SANTO TORIBIO", "SAPAC", "SICO", "TALISAY", "TAMBO", "TANGOB", "TANGUAY", "TIBIG", "TIPACAN" }));
        cbBarangay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangayActionPerformed(evt);
            }
        });

        cbSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSectorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 105, 74));
        jLabel7.setText("Sector:");

        lblBarangay.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay.setText("Barangay :");

        btnAdd.setBackground(new java.awt.Color(129, 182, 115));
        btnAdd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(68, 105, 74));
        btnAdd.setText("ADD");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(129, 182, 115));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(68, 105, 74));
        btnUpdate.setText("UPDATE");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(129, 182, 115));
        btnCancel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(68, 105, 74));
        btnCancel.setText("CANCEL");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(250, 98, 98));
        btnDelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(68, 105, 74));
        btnDelete.setText("DELETE");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 105, 74));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add a Member");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate)
                .addGap(30, 30, 30)
                .addComponent(btnCancel)
                .addGap(30, 30, 30)
                .addComponent(btnDelete)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBarangay)
                                .addGap(30, 30, 30)
                                .addComponent(cbBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(30, 30, 30)
                                .addComponent(cbSector, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIDNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay)
                    .addComponent(cbBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSector, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSearch)
                    .addComponent(cbBarangayFilter, 0, 245, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDate)
                .addGap(15, 15, 15))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(centerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(centerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBarangay5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDate)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBarangayFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(lblBarangay5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.setBackground(new java.awt.Color(218, 243, 210));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/100x100seal.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnRedeemPoints2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints2.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints2.setText("ITEMS AND SECTORS");
        btnRedeemPoints2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints2.setFocusPainted(false);
        btnRedeemPoints2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints2ActionPerformed(evt);
            }
        });

        btnRedeemPoints1.setBackground(new java.awt.Color(218, 243, 210));
        btnRedeemPoints1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints1.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints1.setText("MEMBERS");
        btnRedeemPoints1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints1.setFocusPainted(false);
        btnRedeemPoints1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints1ActionPerformed(evt);
            }
        });

        btnDataTrash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataTrash.setForeground(new java.awt.Color(68, 105, 74));
        btnDataTrash.setText("DATABASES");
        btnDataTrash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTrash.setFocusPainted(false);
        btnDataTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataTrashMouseExited(evt);
            }
        });
        btnDataTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTrashActionPerformed(evt);
            }
        });

        btnInputForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInputForm.setForeground(new java.awt.Color(68, 105, 74));
        btnInputForm.setText("INPUT FORM");
        btnInputForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputForm.setFocusPainted(false);
        btnInputForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputFormActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/login_icon.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Currently logged in");

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(68, 105, 74));
        lblUser.setText("       ");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDataTrash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(80, 80, 80)
                .addComponent(btnDataTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnInputForm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(center, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, 684, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        connect = DatabaseConnection.connectionDB();
        model = (DefaultTableModel) tblTable.getModel();
        
        String delete = "DELETE FROM members WHERE memberID LIKE '" + tfIDNum.getText() + "'";
        
        if (JOptionPane.showConfirmDialog(frame, "Delete member?", "Trash to Cash", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            
            try {
                pre = (PreparedStatement) connect.prepareStatement(delete);
                pre.execute();
                model.setRowCount(0);
                display();
                
            } catch (SQLException ex) {
                Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (tfName.getText().equals("") || cbSector.getSelectedItem().equals("----") || cbBarangay.getSelectedItem().equals("----")){

            JOptionPane.showMessageDialog(this, "Invalid input. Fill in all fields.");
        } else {
            
            connect = DatabaseConnection.connectionDB();
            model = (DefaultTableModel) tblTable.getModel();

            try {
                String barangay = cbBarangay.getSelectedItem().toString();
                String name = tfName.getText();
                String sector = cbSector.getSelectedItem().toString();
                String date = date();
                
                String addMember = "INSERT INTO members (name, barangay, sector, date) VALUES (?, ?, ?, ?)";
                
                pre = (PreparedStatement) connect.prepareStatement(addMember);
                pre.setString(1, name);
                pre.setString(2, barangay);
                pre.setString(3, sector);
                pre.setString(4, date);
                
                pre.execute();
                pre.close();
                
                String memberID = "SELECT * FROM members ORDER BY memberID DESC LIMIT 1";
                String id = "";
                try {
                    pre = (PreparedStatement) connect.prepareStatement(memberID);
                    rs = pre.executeQuery();
                
                    while (rs.next()){
                        id = rs.getString("memberID");
                    }
                    
                    JOptionPane.showMessageDialog(this, "Member Added. \nMember ID: " + id);
                    model.setRowCount(0);
                    display();
                
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
            
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        

        tfName.setText("");
        cbBarangay.setSelectedIndex(0);
        cbSector.setSelectedIndex(0);
        tfIDNum.setText("");
        tfSearch.setText("");
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        if (tblTable.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "No record is selected.");
        } else{
            
            try {
                
                connect = DatabaseConnection.connectionDB();
                model = (DefaultTableModel) tblTable.getModel();
                
                String member = tfName.getText();
                String update = "UPDATE members set name = '" + member + "', barangay = '" + cbBarangay.getSelectedItem().toString() + "', sector = '" + cbSector.getSelectedItem().toString() + "' WHERE memberID LIKE '" + tfIDNum.getText() + "'";
                
                pre = (PreparedStatement) connect.prepareStatement(update);
                
                pre.execute();
                pre.close();
                model.setRowCount(0);
                display();
                
            } catch (SQLException ex) {
                Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        }
        

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbBarangayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBarangayActionPerformed

    private void cbSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSectorActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        try {
            // TODO add your handling code here:
            String update = "SELECT * FROM members WHERE name LIKE '" + tfSearch.getText() + "%'";
            
            pre = (PreparedStatement) connect.prepareStatement(update);
            rs = pre.executeQuery();
            model = (DefaultTableModel) tblTable.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                model.addRow(new Object[]{
                    
                    rs.getString("memberID"),
                    rs.getString("name"),
                    rs.getString("barangay"),
                    rs.getString("sector"),
                    rs.getString("date")
                        
                });
                
            }
            
            pre.execute();
            pre.close();
            
            filter(tfSearch.getText());
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfSearchKeyReleased

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        // TODO add your handling code here:
        int row = tblTable.getSelectedRow();
        String IDnum = tblTable.getValueAt(row, 0).toString();
        String name = tblTable.getValueAt(row, 1).toString();
        String barangay = tblTable.getValueAt(row, 2).toString();
        String sector = tblTable.getValueAt(row, 3).toString();
        String date = tblTable.getValueAt(row, 4).toString();

        int indexBrgy = 0;
        for (int i = 0; i < cbBarangay.getItemCount(); i++) {
            if (barangay.equals(cbBarangay.getItemAt(i))) {
                indexBrgy = i;
            }
        }

        int indexSec = 0;
        for (int i = 0; i < cbSector.getItemCount(); i++) {
            if (sector.equals(cbSector.getItemAt(i))) {
                indexSec = i;
            }
        }

        tfName.setText(name);
        tfIDNum.setText(IDnum);
        cbBarangay.setSelectedIndex(indexBrgy);
        cbSector.setSelectedIndex(indexSec);
        tfDate.setText(date);
    }//GEN-LAST:event_tblTableMouseClicked

    private void cbBarangayFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangayFilterActionPerformed
        // TODO add your handling code here:
        cbBarangay();
    }//GEN-LAST:event_cbBarangayFilterActionPerformed

    private void tfIDNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDNumActionPerformed

    private void btnRedeemPoints2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints2ActionPerformed
        // TODO add your handling code here:

        Options opt = new Options();
        opt.setVisible(true);
        opt.setTitle("Items and Sectors");
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints2ActionPerformed

    private void btnRedeemPoints1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints1ActionPerformed
        // TODO add your handling code here:
        Member member = new Member();
        member.setVisible(true);
        member.setTitle("Members' Records");
        member.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        member.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();

    }//GEN-LAST:event_btnRedeemPoints1ActionPerformed

    private void btnDataTrashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataTrashMouseExited

    }//GEN-LAST:event_btnDataTrashMouseExited

    private void btnDataTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTrashActionPerformed
        DBOptions database = new DBOptions();
        database.setVisible(true);
        database.setTitle("Databases");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnDataTrashActionPerformed

    private void btnInputFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputFormActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.setTitle("Input Form");
        input.pack();
        input.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        input.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnInputFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDataTrash;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInputForm;
    private javax.swing.JButton btnRedeemPoints1;
    private javax.swing.JButton btnRedeemPoints2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbBarangay;
    private javax.swing.JComboBox<String> cbBarangayFilter;
    private javax.swing.JCheckBox cbDate;
    private javax.swing.JComboBox<String> cbSector;
    private javax.swing.JPanel center;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarangay;
    private javax.swing.JLabel lblBarangay5;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel main;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfIDNum;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRowCount;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
