
package TrashToCashSystem;

import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class Options extends javax.swing.JFrame {

    Connection connect;
    PreparedStatement pre;
    ResultSet rs;
    DefaultTableModel item;
    DefaultTableModel sector;
    DefaultTableModel category;
    static int count;

    public Options() {
        initComponents();
        display();
        PopulateCategory();
        
    }

    public void display() {
        try {

            connect = DatabaseConnection.connectionDB();

            item = (DefaultTableModel) tblItem.getModel();
            sector = (DefaultTableModel) tblSector.getModel();
            category = (DefaultTableModel) tblCategory.getModel();
            item.setRowCount(0);
            sector.setRowCount(0);
            category.setRowCount(0);

            String forItem = "SELECT * FROM materials WHERE status = 'unarchived'";

            pre = (PreparedStatement) connect.prepareStatement(forItem);
            rs = pre.executeQuery();

            while (rs.next()) {
                item.addRow(new Object[]{
                    rs.getString("item"),
                    rs.getString("value"),
                    rs.getString("category")
                });
            }

            pre.close();
            rs.close();
            
            String forSector = "SELECT * FROM sector";

            pre = (PreparedStatement) connect.prepareStatement(forSector);
            rs = pre.executeQuery();

            while (rs.next()) {
                sector.addRow(new Object[]{
                    rs.getString("sector")
                });
            }

            pre.close();
            rs.close();
            
            String forCategory = "SELECT * FROM item_category WHERE status = 'enabled'";
            
            pre = (PreparedStatement) connect.prepareStatement(forCategory);
            rs = pre.executeQuery();

            while (rs.next()) {
                category.addRow(new Object[]{
                    rs.getString("category")
                });
            }

            pre.close();
            rs.close();

        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void PopulateCategory(){
        try {
            String categories = "SELECT * FROM item_category";
            pre = (PreparedStatement) connect.prepareStatement(categories);
            rs = pre.executeQuery();
            
            while (rs.next()){
                cbCategory.addItem(rs.getString("category"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        pnlItem = new javax.swing.JPanel();
        btnAddItem = new javax.swing.JButton();
        lblBarangay3 = new javax.swing.JLabel();
        updateItem = new javax.swing.JButton();
        tfValue = new javax.swing.JTextField();
        lblBarangay1 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        lblBarangay6 = new javax.swing.JLabel();
        lblBarangay4 = new javax.swing.JLabel();
        tfItem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnArchiveItem = new javax.swing.JButton();
        pnlCategory = new javax.swing.JPanel();
        lblBarangay8 = new javax.swing.JLabel();
        lblBarangay7 = new javax.swing.JLabel();
        btnDeleteSector1 = new javax.swing.JButton();
        tfCategory = new javax.swing.JTextField();
        btnAddSector1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCategory1 = new javax.swing.JTable();
        pnlSector = new javax.swing.JPanel();
        lblBarangay2 = new javax.swing.JLabel();
        btnDeleteSector = new javax.swing.JButton();
        lblBarangay5 = new javax.swing.JLabel();
        tfSector = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSector = new javax.swing.JTable();
        btnAddSector = new javax.swing.JButton();
        sidebar14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        btnRedeemPoints29 = new javax.swing.JButton();
        btnRedeemPoints30 = new javax.swing.JButton();
        btnDataTrash14 = new javax.swing.JButton();
        btnInputForm14 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblUser13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(238, 248, 235));
        main.setPreferredSize(new java.awt.Dimension(1127, 686));

        center.setBackground(new java.awt.Color(238, 248, 235));
        center.setPreferredSize(new java.awt.Dimension(898, 686));

        pnlItem.setBackground(new java.awt.Color(196, 226, 187));

        btnAddItem.setBackground(new java.awt.Color(129, 182, 115));
        btnAddItem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(68, 105, 74));
        btnAddItem.setText("ADD");
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItem.setFocusPainted(false);
        btnAddItem.setPreferredSize(new java.awt.Dimension(103, 34));
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        lblBarangay3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay3.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay3.setText("Item:");

        updateItem.setBackground(new java.awt.Color(129, 182, 115));
        updateItem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        updateItem.setForeground(new java.awt.Color(68, 105, 74));
        updateItem.setText("UPDATE");
        updateItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateItem.setFocusPainted(false);
        updateItem.setPreferredSize(new java.awt.Dimension(103, 34));
        updateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemActionPerformed(evt);
            }
        });

        tfValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValueActionPerformed(evt);
            }
        });

        lblBarangay1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblBarangay1.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarangay1.setText("ADD ITEM");

        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        lblBarangay6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay6.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay6.setText("Category:");

        lblBarangay4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay4.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay4.setText("Value:");

        tfItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Value", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        btnArchiveItem.setBackground(new java.awt.Color(129, 182, 115));
        btnArchiveItem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnArchiveItem.setForeground(new java.awt.Color(68, 105, 74));
        btnArchiveItem.setText("ARCHIVE");
        btnArchiveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArchiveItem.setFocusPainted(false);
        btnArchiveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchiveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBarangay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlItemLayout.createSequentialGroup()
                        .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarangay3)
                            .addComponent(lblBarangay4))
                        .addGap(35, 35, 35)
                        .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValue)
                            .addComponent(tfItem)))
                    .addGroup(pnlItemLayout.createSequentialGroup()
                        .addComponent(lblBarangay6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnArchiveItem)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBarangay1)
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay3)
                    .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay4)
                    .addComponent(tfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay6)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArchiveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pnlCategory.setBackground(new java.awt.Color(196, 226, 187));

        lblBarangay8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblBarangay8.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarangay8.setText("ADD CATEGORY");

        lblBarangay7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay7.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay7.setText("Category: ");

        btnDeleteSector1.setBackground(new java.awt.Color(129, 182, 115));
        btnDeleteSector1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDeleteSector1.setForeground(new java.awt.Color(68, 105, 74));
        btnDeleteSector1.setText("DISABLE");
        btnDeleteSector1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteSector1.setFocusPainted(false);
        btnDeleteSector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSector1ActionPerformed(evt);
            }
        });

        tfCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCategoryActionPerformed(evt);
            }
        });

        btnAddSector1.setBackground(new java.awt.Color(129, 182, 115));
        btnAddSector1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddSector1.setForeground(new java.awt.Color(68, 105, 74));
        btnAddSector1.setText("ADD");
        btnAddSector1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSector1.setFocusPainted(false);
        btnAddSector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSector1ActionPerformed(evt);
            }
        });

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCategory);

        tblCategory1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCategory1);

        javax.swing.GroupLayout pnlCategoryLayout = new javax.swing.GroupLayout(pnlCategory);
        pnlCategory.setLayout(pnlCategoryLayout);
        pnlCategoryLayout.setHorizontalGroup(
            pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblBarangay8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCategoryLayout.createSequentialGroup()
                                .addComponent(lblBarangay7)
                                .addGap(32, 32, 32)
                                .addComponent(tfCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCategoryLayout.createSequentialGroup()
                        .addComponent(btnAddSector1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSector1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        pnlCategoryLayout.setVerticalGroup(
            pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBarangay8)
                .addGap(12, 12, 12)
                .addGroup(pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay7)
                    .addComponent(tfCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSector1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSector1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnlSector.setBackground(new java.awt.Color(196, 226, 187));

        lblBarangay2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblBarangay2.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarangay2.setText("ADD SECTOR");

        btnDeleteSector.setBackground(new java.awt.Color(129, 182, 115));
        btnDeleteSector.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDeleteSector.setForeground(new java.awt.Color(68, 105, 74));
        btnDeleteSector.setText("DELETE");
        btnDeleteSector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteSector.setFocusPainted(false);
        btnDeleteSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSectorActionPerformed(evt);
            }
        });

        lblBarangay5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay5.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay5.setText("Sector:");

        tfSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSectorActionPerformed(evt);
            }
        });

        tblSector.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Sector "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSector);

        btnAddSector.setBackground(new java.awt.Color(129, 182, 115));
        btnAddSector.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddSector.setForeground(new java.awt.Color(68, 105, 74));
        btnAddSector.setText("ADD");
        btnAddSector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSector.setFocusPainted(false);
        btnAddSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSectorLayout = new javax.swing.GroupLayout(pnlSector);
        pnlSector.setLayout(pnlSectorLayout);
        pnlSectorLayout.setHorizontalGroup(
            pnlSectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSectorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSectorLayout.createSequentialGroup()
                        .addComponent(lblBarangay5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSector, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSectorLayout.createSequentialGroup()
                        .addComponent(btnAddSector, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteSector, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSectorLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblBarangay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnlSectorLayout.setVerticalGroup(
            pnlSectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSectorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBarangay2)
                .addGap(18, 18, 18)
                .addGroup(pnlSectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay5)
                    .addComponent(tfSector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSector, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSector, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addComponent(pnlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlSector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        sidebar14.setBackground(new java.awt.Color(218, 243, 210));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/100x100seal.png"))); // NOI18N
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnRedeemPoints29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints29.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints29.setText("ITEMS AND SECTORS");
        btnRedeemPoints29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints29.setFocusPainted(false);
        btnRedeemPoints29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints29ActionPerformed(evt);
            }
        });

        btnRedeemPoints30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints30.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints30.setText("MEMBERS");
        btnRedeemPoints30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints30.setFocusPainted(false);
        btnRedeemPoints30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints30ActionPerformed(evt);
            }
        });

        btnDataTrash14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataTrash14.setForeground(new java.awt.Color(68, 105, 74));
        btnDataTrash14.setText("DATABASES");
        btnDataTrash14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTrash14.setFocusPainted(false);
        btnDataTrash14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataTrash14MouseExited(evt);
            }
        });
        btnDataTrash14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTrash14ActionPerformed(evt);
            }
        });

        btnInputForm14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInputForm14.setForeground(new java.awt.Color(68, 105, 74));
        btnInputForm14.setText("INPUT FORM");
        btnInputForm14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputForm14.setFocusPainted(false);
        btnInputForm14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputForm14ActionPerformed(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/login_icon.png"))); // NOI18N

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Currently logged in");

        lblUser13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUser13.setForeground(new java.awt.Color(68, 105, 74));
        lblUser13.setText("       ");

        javax.swing.GroupLayout sidebar14Layout = new javax.swing.GroupLayout(sidebar14);
        sidebar14.setLayout(sidebar14Layout);
        sidebar14Layout.setHorizontalGroup(
            sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar14Layout.createSequentialGroup()
                .addGroup(sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputForm14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedeemPoints29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDataTrash14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebar14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(lblUser13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebar14Layout.setVerticalGroup(
            sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebar14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel42)
                .addGap(80, 80, 80)
                .addComponent(btnDataTrash14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnInputForm14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedeemPoints29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(sidebar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel43)
                    .addGroup(sidebar14Layout.createSequentialGroup()
                        .addComponent(lblUser13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel44)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(center, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(center, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemActionPerformed

    private void tfValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValueActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed

        connect = DatabaseConnection.connectionDB();
        
        
        try {
            if (JOptionPane.showConfirmDialog(frame, "Add Record?", "Trash to Cash", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {

                String itemname = tfItem.getText();
                double value = Double.parseDouble(tfValue.getText());
                
                String ifItemExists = "SELECT * FROM materials WHERE item LIKE '" + itemname + "'";
                pre = (PreparedStatement) connect.prepareStatement(ifItemExists);
                rs = pre.executeQuery();
                
                if (rs.next()){
                    JOptionPane.showMessageDialog(frame, "Item already exits.");
                    pre.close();
                    rs.close();
                } else{
                    pre.close();
                    rs.close();
                    
                    String addItem = "INSERT INTO materials VALUES (?, ?, ?, ?)";

                    pre = (PreparedStatement) connect.prepareStatement(addItem);
                    pre.setString(1, itemname);
                    pre.setString(2, String.format("%.2f", value));
                    pre.setString(3, cbCategory.getSelectedItem().toString());
                    pre.setString(4, "unarchived");
                    pre.execute();
                    display();
                    pre.close();
                    
                    count += 1;
                    
                    char ch = '_';
                    itemname = itemname.toLowerCase();
                    itemname = itemname.replace(' ', ch);
                    String addColumnItem = "ALTER TABLE items ADD COLUMN " + itemname + " int (11) DEFAULT 0";
                    pre = (PreparedStatement) connect.prepareStatement(addColumnItem);
                    pre.execute();
                    pre.close();
                    
                }
                
                tfItem.setText("");
                tfValue.setText("");
                cbCategory.setSelectedItem("");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAddItemActionPerformed

    private void tfSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSectorActionPerformed

    private void btnAddSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSectorActionPerformed
        // TODO add your handling code here:
        try {
            
            connect = DatabaseConnection.connectionDB();
            if (JOptionPane.showConfirmDialog(frame, "Add Record?", "Trash to Cash", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String addSector = "INSERT INTO sector VALUES (?)";

                pre = (PreparedStatement) connect.prepareStatement(addSector);
                pre.setString(1, tfSector.getText());

                pre.execute();
                display();
                pre.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddSectorActionPerformed

    private JFrame frame;
    private void btnArchiveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveItemActionPerformed
        try {
            // TODO add your handling code here:
            
            connect = DatabaseConnection.connectionDB();
            if (JOptionPane.showConfirmDialog(frame, "Archive Record?", "Trash to Cash", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String archItem = "UPDATE materials set status = 'archived' WHERE item = '" + tfItem.getText() + "'";

                pre = (PreparedStatement) connect.prepareStatement(archItem);

                pre.execute();
                display();
                pre.close();
                
                tfItem.setText("");
                tfValue.setText("");
                cbCategory.setSelectedItem("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchiveItemActionPerformed

    private void btnDeleteSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSectorActionPerformed
        // TODO add your handling code here:
        try {
            
            connect = DatabaseConnection.connectionDB();
            if (JOptionPane.showConfirmDialog(frame, "Delete Record?", "Trash to Cash", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                String delSector = "DELETE FROM sector WHERE sector = '" + tfSector.getText() + "'";

                pre = (PreparedStatement) connect.prepareStatement(delSector);

                pre.execute();
                display();
                pre.close();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteSectorActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        int index = tblItem.getSelectedRow();
        String itemname = tblItem.getValueAt(index, 0).toString();
        String value = tblItem.getValueAt(index, 1).toString();
        String categoryname = tblItem.getValueAt(index, 2).toString();
        
        tfItem.setText(itemname);
        tfValue.setText(value);
        cbCategory.setSelectedItem(categoryname);
    }//GEN-LAST:event_tblItemMouseClicked

    private void updateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemActionPerformed
        try {
            // TODO add your handling code here:
            connect = DatabaseConnection.connectionDB();
            String update = "UPDATE materials SET value = '" + tfValue.getText() + "', category = '" + cbCategory.getSelectedItem().toString() + "' WHERE item LIKE '" + tfItem.getText() + "'";
            
            pre = (PreparedStatement) connect.prepareStatement (update);
            pre.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateItemActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void tfCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCategoryActionPerformed

    private void btnAddSector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSector1ActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "INSERT INTO item_category (category, status) VALUES (?, ?)";
            pre = (PreparedStatement) connect.prepareStatement(sql);
            pre.setString(1, tfCategory.getText());
            pre.setString(2, "enabled");
            pre.execute();
            pre.close();
            
            String addCategoryCol = "ALTER TABLE datarecord ADD COLUMN " + tfCategory.getText() + " double";
            pre = (PreparedStatement) connect.prepareStatement(addCategoryCol);
            pre.execute();
            pre.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddSector1ActionPerformed

    private void btnDeleteSector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSector1ActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "UPDATE item_category SET status = 'disabled' WHERE category LIKE '" + tfCategory.getText() + "'";
            pre = (PreparedStatement) connect.prepareStatement(sql);
            pre.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteSector1ActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        int index = tblCategory.getSelectedRow();
        tfCategory.setText(tblCategory.getValueAt(index, 1).toString());
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void btnRedeemPoints29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints29ActionPerformed
        // TODO add your handling code here:

        Options opt = new Options();
        opt.setVisible(true);
        opt.setTitle("Items and Sectors");
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints29ActionPerformed

    private void btnRedeemPoints30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints30ActionPerformed
        // TODO add your handling code here:
        Member member = new Member();
        member.setVisible(true);
        member.setTitle("Members' Records");
        member.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        member.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints30ActionPerformed

    private void btnDataTrash14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataTrash14MouseExited

    }//GEN-LAST:event_btnDataTrash14MouseExited

    private void btnDataTrash14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTrash14ActionPerformed
        DBOptions database = new DBOptions();
        database.setVisible(true);
        database.setTitle("Databases");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnDataTrash14ActionPerformed

    private void btnInputForm14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputForm14ActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.setTitle("Input Form");
        input.pack();
        input.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        input.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnInputForm14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddSector;
    private javax.swing.JButton btnAddSector1;
    private javax.swing.JButton btnArchiveItem;
    private javax.swing.JButton btnDataTrash14;
    private javax.swing.JButton btnDeleteSector;
    private javax.swing.JButton btnDeleteSector1;
    private javax.swing.JButton btnInputForm14;
    private javax.swing.JButton btnRedeemPoints29;
    private javax.swing.JButton btnRedeemPoints30;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JPanel center;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBarangay1;
    private javax.swing.JLabel lblBarangay2;
    private javax.swing.JLabel lblBarangay3;
    private javax.swing.JLabel lblBarangay4;
    private javax.swing.JLabel lblBarangay5;
    private javax.swing.JLabel lblBarangay6;
    private javax.swing.JLabel lblBarangay7;
    private javax.swing.JLabel lblBarangay8;
    private javax.swing.JLabel lblUser13;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlCategory;
    private javax.swing.JPanel pnlItem;
    private javax.swing.JPanel pnlSector;
    private javax.swing.JPanel sidebar14;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTable tblCategory1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSector;
    private javax.swing.JTextField tfCategory;
    private javax.swing.JTextField tfItem;
    private javax.swing.JTextField tfSector;
    private javax.swing.JTextField tfValue;
    private javax.swing.JButton updateItem;
    // End of variables declaration//GEN-END:variables
}
