
package TrashToCashSystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class RedeemForm extends javax.swing.JFrame {

    Connection connect = null;
    PreparedStatement pre = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    DataTrash data = new DataTrash();

    
    public RedeemForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        displayTable();
        
    }
    
    private String date(){
        
        String date;
        date = (java.time.LocalDate.now().toString());

        return date;
    }
    
    private JFrame frame;
    
    public void filter(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (model);
        tblRedeem.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter (query));
    }
    
    private void displayTable(){
        model = (DefaultTableModel) tblRedeem.getModel();
        
        try {
            connect = DatabaseConnection.connectionDB();
            
            String sql = "SELECT * FROM total_points";
            pre = (PreparedStatement) connect.prepareStatement(sql);
            rs = pre.executeQuery();
            
            while (rs.next()){
                
                model.addRow(new Object[]{
                
                rs.getString("memberID"),
                rs.getString("name"),
                rs.getString("barangay"),
                rs.getString("sector"),
                rs.getDouble("totalpoints")});
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RedeemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnInputForm = new javax.swing.JButton();
        btnRedeemPoints = new javax.swing.JButton();
        btnRedeemPoints1 = new javax.swing.JButton();
        btnRedeemPoints2 = new javax.swing.JButton();
        btnDataTrash = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        lblBarangay4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRedeem = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBarangay1 = new javax.swing.JLabel();
        lblBarangay2 = new javax.swing.JLabel();
        lblBarangay5 = new javax.swing.JLabel();
        lblBarangay6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfBarangay = new javax.swing.JTextField();
        tfSector = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        lblBarangay3 = new javax.swing.JLabel();
        tfmemberID = new javax.swing.JTextField();
        lblBarangay7 = new javax.swing.JLabel();
        tfRedeem = new javax.swing.JTextField();
        btnRedeem = new javax.swing.JButton();
        btnRedeem3 = new javax.swing.JButton();

        jButton1.setForeground(new java.awt.Color(68, 105, 74));
        jButton1.setText("MAIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(240, 80));

        main.setBackground(new java.awt.Color(238, 248, 235));
        main.setPreferredSize(new java.awt.Dimension(1127, 686));

        sidebar.setBackground(new java.awt.Color(218, 243, 210));
        sidebar.setPreferredSize(new java.awt.Dimension(223, 593));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/100x100seal.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnInputForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInputForm.setForeground(new java.awt.Color(68, 105, 74));
        btnInputForm.setText("INPUT FORM");
        btnInputForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputForm.setFocusPainted(false);
        btnInputForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputFormActionPerformed(evt);
            }
        });

        btnRedeemPoints.setBackground(new java.awt.Color(218, 243, 210));
        btnRedeemPoints.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints.setText("REDEEM POINTS");
        btnRedeemPoints.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints.setFocusPainted(false);
        btnRedeemPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPointsActionPerformed(evt);
            }
        });

        btnRedeemPoints1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints1.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints1.setText("MEMBERS");
        btnRedeemPoints1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints1.setFocusPainted(false);
        btnRedeemPoints1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints1ActionPerformed(evt);
            }
        });

        btnRedeemPoints2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRedeemPoints2.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeemPoints2.setText("ITEMS AND SECTORS");
        btnRedeemPoints2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeemPoints2.setFocusPainted(false);
        btnRedeemPoints2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemPoints2ActionPerformed(evt);
            }
        });

        btnDataTrash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataTrash.setForeground(new java.awt.Color(68, 105, 74));
        btnDataTrash.setText("DATABASES");
        btnDataTrash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTrash.setFocusPainted(false);
        btnDataTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataTrashMouseExited(evt);
            }
        });
        btnDataTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTrashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRedeemPoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInputForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRedeemPoints1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRedeemPoints2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(btnDataTrash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(89, 89, 89)
                .addComponent(btnDataTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedeemPoints1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInputForm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedeemPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedeemPoints2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );

        center.setBackground(new java.awt.Color(238, 248, 235));
        center.setPreferredSize(new java.awt.Dimension(898, 674));

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        lblBarangay4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay4.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay4.setText("Search:");

        tblRedeem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Barangay", "Sector", "Total Points"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRedeem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRedeemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRedeem);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system_icon/TRASH TO CASH LOGO SMALL 2.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(196, 226, 187));

        lblBarangay1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay1.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay1.setText("Barangay :");

        lblBarangay2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay2.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay2.setText("Name: ");

        lblBarangay5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay5.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay5.setText("Sector:");

        lblBarangay6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay6.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay6.setText("Total Points:");

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        lblBarangay3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay3.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay3.setText("MemberID:");

        lblBarangay7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBarangay7.setForeground(new java.awt.Color(68, 105, 74));
        lblBarangay7.setText("Redeem:");

        tfRedeem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRedeemActionPerformed(evt);
            }
        });

        btnRedeem.setBackground(new java.awt.Color(129, 182, 115));
        btnRedeem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRedeem.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeem.setText("REDEEM POINTS");
        btnRedeem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeemActionPerformed(evt);
            }
        });

        btnRedeem3.setBackground(new java.awt.Color(129, 182, 115));
        btnRedeem3.setForeground(new java.awt.Color(68, 105, 74));
        btnRedeem3.setText("Go to Redeem History");
        btnRedeem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedeem3.setFocusable(false);
        btnRedeem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedeem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnRedeem3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblBarangay3)
                                .addGap(50, 50, 50)
                                .addComponent(tfmemberID))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBarangay1)
                                    .addComponent(lblBarangay2)
                                    .addComponent(lblBarangay5)
                                    .addComponent(lblBarangay6)
                                    .addComponent(lblBarangay7))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRedeem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfRedeem)
                                    .addComponent(tfSector, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfBarangay, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfName)
                                    .addComponent(tfTotal))))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay3)
                    .addComponent(tfmemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay1)
                    .addComponent(tfBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay5)
                    .addComponent(tfSector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay6)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarangay7)
                    .addComponent(tfRedeem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnRedeem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRedeem3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(centerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBarangay4)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(538, 538, 538))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBarangay4))
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(center, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedeemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM total_points WHERE name LIKE '" + tfName.getText()+ "' && barangay LIKE '" + tfBarangay.getText() + "' && sector LIKE '" +tfSector.getText() + "'";
        
        try {
            pre = (PreparedStatement) connect.prepareStatement(sql);
            rs = pre.executeQuery();
            double totalpts;
            while (rs.next()){
                if (Double.parseDouble(tfRedeem.getText()) < rs.getDouble("totalpoints")){
                    totalpts = rs.getDouble("totalpoints") - Double.parseDouble(tfRedeem.getText());
                    
                    String query = "UPDATE total_points set totalpoints = '" + totalpts + "' WHERE name LIKE '" + tfName.getText()+ "' && barangay LIKE '" + tfBarangay.getText() + "' && sector LIKE '" +tfSector.getText() + "'";
            
                    pre = (PreparedStatement) connect.prepareStatement(query);
                    if (JOptionPane.showConfirmDialog(frame, "Confirm Point Redemption?", "Redeem Points", 
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
                        
                        pre.execute();
                        model.setRowCount(0);
                        displayTable();
                        
                    }
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Not enough environmental points.");
                }
                
            }
            
            pre.close();
            rs.close();
            int memberID = Integer.parseInt(tfmemberID.getText().toString());
            
            String recordRedemption = "INSERT INTO redeem_history VALUES (?, ?, ?, ?, ?, ?, ?)";
            
            pre.setInt(1, memberID);
            pre.setString(2, tfName.getText());
            pre.setString(3, tfBarangay.getText());
            pre.setString(4, tfSector.getText());
            pre.setString(5, date());
            pre.setDouble(6, Double.parseDouble(tfRedeem.getText().toString()));
            pre.setDouble(7, Double.parseDouble(tfTotal.getText().toString()));
            pre = (PreparedStatement) connect.prepareStatement(recordRedemption);
            pre.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RedeemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnRedeemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfRedeemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRedeemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRedeemActionPerformed

    private void tblRedeemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRedeemMouseClicked
        // TODO add your handling code here:
        int index = tblRedeem.getSelectedRow();
        tfmemberID.setText(model.getValueAt(index, 0).toString());
        tfName.setText(model.getValueAt(index, 1).toString());
        tfBarangay.setText(model.getValueAt(index, 2).toString());
        tfSector.setText(model.getValueAt(index, 3).toString());
        tfTotal.setText(model.getValueAt(index, 4).toString());
        
    }//GEN-LAST:event_tblRedeemMouseClicked

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String sql = "SELECT * FROM total_points where name LIKE '" + tfSearch.getText() + "%'";

        try{
            connect = DatabaseConnection.connectionDB();
            pre= connect.prepareStatement(sql);
            rs = pre.executeQuery();
            model = (DefaultTableModel)tblRedeem.getModel();
            model.setRowCount(0);

            while (rs.next()){

                model.addRow(new Object[]{

                    rs.getString("name"),
                    rs.getString("barangay"),
                    rs.getString("sector"),
                    rs.getDouble("totalpoints")});

        }

        }catch (SQLException e)
        {
            JOptionPane.showMessageDialog (null, e);
        }

        filter (tfSearch.getText());
    }//GEN-LAST:event_tfSearchKeyReleased

    private void btnInputFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputFormActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.setTitle("Input Form");
        input.pack();
        input.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        input.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnInputFormActionPerformed

    private void btnRedeemPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPointsActionPerformed
        // TODO add your handling code here:
        RedeemForm redeem = new RedeemForm();
        redeem.setVisible(true);
        redeem.setTitle("Redeem Form");
        redeem.pack();
        redeem.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        redeem.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPointsActionPerformed

    private void btnRedeemPoints1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints1ActionPerformed
        // TODO add your handling code here:
        Member member = new Member();
        member.setVisible(true);
        member.setTitle("Members' Records");
        member.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        member.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints1ActionPerformed

    private void btnRedeemPoints2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeemPoints2ActionPerformed
        // TODO add your handling code here:
        Options opt = new Options();
        opt.setVisible(true);
        opt.setTitle("Items and Sectors");
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRedeemPoints2ActionPerformed

    private void btnDataTrashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataTrashMouseExited

    }//GEN-LAST:event_btnDataTrashMouseExited

    private void btnDataTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTrashActionPerformed
        DBOptions database = new DBOptions();
        database.setVisible(true);
        database.setTitle("Databases");
        database.pack();
        database.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        database.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnDataTrashActionPerformed

    private void btnRedeem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedeem3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnRedeem3ActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedeemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedeemForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataTrash;
    private javax.swing.JButton btnInputForm;
    private javax.swing.JButton btnRedeem;
    private javax.swing.JButton btnRedeem3;
    private javax.swing.JButton btnRedeemPoints;
    private javax.swing.JButton btnRedeemPoints1;
    private javax.swing.JButton btnRedeemPoints2;
    private javax.swing.JPanel center;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarangay1;
    private javax.swing.JLabel lblBarangay2;
    private javax.swing.JLabel lblBarangay3;
    private javax.swing.JLabel lblBarangay4;
    private javax.swing.JLabel lblBarangay5;
    private javax.swing.JLabel lblBarangay6;
    private javax.swing.JLabel lblBarangay7;
    private javax.swing.JPanel main;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tblRedeem;
    private javax.swing.JTextField tfBarangay;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRedeem;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSector;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfmemberID;
    // End of variables declaration//GEN-END:variables
}
